version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`217.154.81.219`)"
      - "traefik.http.routers.react-app.entrypoints=web"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
