version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`yourdomain.com`)" # Замените на ваш домен
      - "traefik.http.routers.react-app.entrypoints=websecure"
      - "traefik.http.routers.react-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
